name: Daily Motivation Email
on:
  schedule:
    - cron: "0 20 * * *"  # 8h Paris (6h UTC)
  workflow_dispatch:  # Permet de déclencher manuellement

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Send email
        run: npx ts-node src/sendEmail.ts
        env:
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
