name: Daily Motivation Email
on:
  schedule:
    - cron: "0 5 * * *"  # 7h Paris (5h UTC en été)
  workflow_dispatch:

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install ts-node typescript --save-dev && npm ci

      - name: Run script
        run: npx ts-node src/sendEmail.ts
        env:
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
