name: Daily Motivation Email
on:
  schedule:
    - cron: "0 5 * * *"  # 7h Paris
  workflow_dispatch:

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm install -g ts-node typescript
          npm ci
          
      - name: Run script (METHODE ALTERNATIVE)
        run: |
          node -e "require('ts-node').register(); require('./src/sendEmail.ts')"
        env:
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
